POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impha2UiLCJpZCI6IjVhOTFiZjhmMjEyMmE1ZGE0MmNkMTdkNyIsImlhdCI6MTUxOTUwODQwN30.SAzj5_gNFnFtREDdaJsu0KEZkRc2t2MABBFf2i-pJHM

{
    "author": "MIKA WALTARI",
    "title": "MINUHE EGYPTIAN",
    "url": "h",
    "likes": 0,
    "userid": "5a91bf8f2122a5da42cd17d7"
}