POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "toni ja joni",
    "author": "jonna joutseno",
    "url": "http://www.google.fi",
    "likes": 0,
    "userId": "5a91bf8f2122a5da42cd17d7"
}