PUT http://localhost:3001/api/blogs/5a8ed5d245b5e678f1f23229
content-type: application/json

{
    "_id":"5a8ed5d245b5e678f1f23229",
    "author":"jonna joutsena",
    "url":"http://www.google.com",
    "likes":10,
    "__v":0
}